[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
webpki = "0.21"
tokio-rustls = { path = "../.." }
tokio = "0.1"
clap = "2"
webpki-roots = "0.17"
tokio-stdin-stdout = "0.1"
